use serde::{Deserialize, Serialize};

/// Custom serde for `[u8; 64]` — serde's derive only covers arrays up to length 32.
mod serde_sig64 {
    use serde::{Deserializer, Serializer};

    pub fn serialize<S: Serializer>(v: &[u8; 64], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_bytes(v)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<[u8; 64], D::Error> {
        struct Visitor;
        impl<'de> serde::de::Visitor<'de> for Visitor {
            type Value = [u8; 64];
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                write!(f, "64 bytes")
            }
            fn visit_bytes<E: serde::de::Error>(self, v: &[u8]) -> Result<[u8; 64], E> {
                v.try_into()
                    .map_err(|_| E::custom("expected 64 bytes for signature"))
            }
            fn visit_byte_buf<E: serde::de::Error>(self, v: Vec<u8>) -> Result<[u8; 64], E> {
                v.try_into()
                    .map_err(|_| E::custom("expected 64 bytes for signature"))
            }
            fn visit_seq<A: serde::de::SeqAccess<'de>>(
                self,
                mut seq: A,
            ) -> Result<[u8; 64], A::Error> {
                let mut arr = [0u8; 64];
                for (i, slot) in arr.iter_mut().enumerate() {
                    *slot = seq
                        .next_element()?
                        .ok_or_else(|| serde::de::Error::invalid_length(i, &"64 bytes"))?;
                }
                Ok(arr)
            }
        }
        d.deserialize_bytes(Visitor)
    }
}

pub const MSG_VERSION: u8 = 1;
pub const MAX_TTL_SECONDS: u32 = 60 * 60 * 24 * 30; // 30 days
pub const MAX_BODY_BYTES: usize = 65_535;
pub const MAX_SUBJECT_BYTES: usize = 255;
pub const MAX_ENVELOPE_BYTES: usize = 512 * 1024; // 512 KB
pub const RELAY_REPLICATION_FACTOR: usize = 3;
pub const TIME_MSG_MAGIC: &[u8; 4] = b"TIME";

/// Plaintext message — never stored or transmitted in this form.
/// Encrypted into TimeEnvelope before leaving the wallet.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeMessage {
    pub version: u8,
    pub sender_pubkey: [u8; 32],
    pub recipient_addr: String,
    pub timestamp: i64,
    pub ttl_seconds: u32,
    /// bit 0 = request_read_receipt, bit 1 = reply_allowed
    pub flags: u8,
    pub thread_id: Option<[u8; 32]>,
    pub subject: Vec<u8>,
    pub body: Vec<u8>,
}

impl TimeMessage {
    pub fn request_read_receipt(&self) -> bool {
        self.flags & 0x01 != 0
    }
    pub fn reply_allowed(&self) -> bool {
        self.flags & 0x02 != 0
    }
}

/// Wire envelope — stored in the relay and transmitted over P2P.
/// `ciphertext_payload` is XChaCha20-Poly1305 encrypted TimeMessage (CBOR).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeEnvelope {
    pub version: u8,
    /// SHA-256(ciphertext_payload)
    pub msg_id: [u8; 32],
    /// SHA-256(recipient TIME1 address bytes)
    pub recipient_addr_hash: [u8; 32],
    pub sender_pubkey: [u8; 32],
    pub ephemeral_pubkey: [u8; 32],
    pub nonce: [u8; 24],
    pub ciphertext_payload: Vec<u8>,
    /// Ed25519 sig over: msg_id || recipient_addr_hash || nonce || ciphertext_payload
    #[serde(with = "serde_sig64")]
    pub sender_sig: [u8; 64],
    pub created_at: i64,
    pub ttl_seconds: u32,
    pub flags: u8,
}

impl TimeEnvelope {
    pub fn expires_at(&self) -> i64 {
        self.created_at + self.ttl_seconds as i64
    }

    pub fn is_expired(&self) -> bool {
        chrono::Utc::now().timestamp() > self.expires_at()
    }

    pub fn serialise(&self) -> Result<Vec<u8>, MessageError> {
        serde_cbor::to_vec(self).map_err(|e| MessageError::Serialisation(e.to_string()))
    }

    pub fn deserialise(bytes: &[u8]) -> Result<Self, MessageError> {
        serde_cbor::from_slice(bytes).map_err(|e| MessageError::Serialisation(e.to_string()))
    }
}

/// Signed read receipt — generated by recipient wallet after user opens message.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReadAck {
    pub version: u8,
    pub msg_id: [u8; 32],
    pub sender_addr: String,
    pub read_at: i64,
    /// Ed25519 sig over: "time-ack-v1" || msg_id || sender_addr_bytes || read_at_le_bytes
    #[serde(with = "serde_sig64")]
    pub recipient_sig: [u8; 64],
}

impl ReadAck {
    pub fn signing_bytes(msg_id: &[u8; 32], sender_addr: &str, read_at: i64) -> Vec<u8> {
        let mut v = b"time-ack-v1".to_vec();
        v.extend_from_slice(msg_id);
        v.extend_from_slice(sender_addr.as_bytes());
        v.extend_from_slice(&read_at.to_le_bytes());
        v
    }
}

/// Stored by relay when it observes the recipient fetch an envelope.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryEvent {
    pub msg_id: [u8; 32],
    pub delivered_at: i64,
    pub relay_pubkey: [u8; 32],
    /// Ed25519 sig over: "time-delivery-v1" || msg_id || delivered_at_le_bytes
    #[serde(with = "serde_sig64")]
    pub relay_sig: [u8; 64],
}

/// Stored by relay when a message expires before delivery.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpiryNotice {
    pub msg_id: [u8; 32],
    pub recipient_hash: [u8; 32],
    pub expired_at: i64,
    #[serde(with = "serde_sig64")]
    pub relay_sig: [u8; 64],
}

/// Confirmed storage receipt returned by relay to sender after MsgSubmit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelayStorageAck {
    pub msg_id: [u8; 32],
    pub stored_at: i64,
    pub expires_at: i64,
    pub relay_pubkey: [u8; 32],
    /// Ed25519 sig over: "time-store-v1" || msg_id || stored_at_le_bytes
    #[serde(with = "serde_sig64")]
    pub relay_sig: [u8; 64],
}

/// Per-message delivery status — tracked by sender wallet via RPC.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum MessageStatus {
    Pending,
    Delivered,
    Read,
    Expired,
    Failed,
}

impl MessageStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            MessageStatus::Pending => "pending",
            MessageStatus::Delivered => "delivered",
            MessageStatus::Read => "read",
            MessageStatus::Expired => "expired",
            MessageStatus::Failed => "failed",
        }
    }
}

#[derive(Debug, thiserror::Error)]
pub enum MessageError {
    #[error("Serialisation error: {0}")]
    Serialisation(String),
    #[error("Encryption error: {0}")]
    Encryption(String),
    #[error("Decryption error: {0}")]
    Decryption(String),
    #[error("Invalid signature")]
    InvalidSignature,
    #[error("Message too large: {0} bytes (max {1})")]
    TooLarge(usize, usize),
    #[error("TTL too long: {0}s (max {1}s)")]
    TtlTooLong(u32, u32),
    #[error("Storage error: {0}")]
    Storage(String),
    #[error("Not a relay node (requires Silver or Gold tier)")]
    NotRelayEligible,
    #[error("Recipient pubkey not found for address {0}")]
    PubkeyNotFound(String),
}
